# Solving for $x$

In [1]:
import sympy as sym
from IPython.display import display, Math

In [2]:
x = sym.symbols('x')

expr = 2*x + 4 - 9

sym.solve(expr)

[5/2]

In [9]:
display(Math('\\text{The solution to } %s \\text{ is x=} %g' %(sym.latex(expr), sym.solve(expr)[0])))

<IPython.core.display.Math object>

In [20]:
expr = x**2 - 4

sol = sym.solve(expr)

for i in range(len(sol)):
    print('Solution #' + str(i + 1) + ' is ' + str(sol[i]))

Solution #1 is -2
Solution #2 is 2


In [24]:
y = sym.symbols('y')
expr = x/4 - x*y + 5
sym.solve(expr,y)

[(x + 20)/(4*x)]

## Exercise 1

In [32]:
# 1
q = sym.symbols('q')

eq = 3*q + 4/q + 3 - 5*q - 1/q - 1
display(Math('q = ' + sym.latex(sym.solve(eq,q))))

<IPython.core.display.Math object>

In [36]:
 # 2
eq = 2*q + 3*(q**2) - 5/q - 4/(q**3)
display(Math(sym.latex(eq)))
display(Math(sym.latex(sym.simplify(eq))))
display(Math(sym.latex(sym.cancel(eq))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [50]:
# 3
expr = (sym.sqrt(3) + sym.sqrt(15)*q) / (sym.sqrt(2) + sym.sqrt(10)*q)
display(Math(sym.latex(expr)))
display(Math(sym.latex(sym.simplify(expr))))
expr.subs(q,-83).evalf()

<IPython.core.display.Math object>

<IPython.core.display.Math object>

1.22474487139159

# Expanding terms

In [66]:
from sympy.abc import x,y

term1 = (4*x + 5)
term2 = x

display(Math(sym.latex(term1 * term2)))
display(Math(sym.latex(sym.expand(term1*term2))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [67]:
term3 = x - 7
display(Math(sym.latex(term1 * term3)))
display(Math(sym.latex(sym.expand(term1 * term3))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [69]:
expr = x*(2*y**2 - 5**x/x)
display(Math(sym.latex(expr)))
display(Math(sym.latex(sym.expand(expr))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [70]:
%whos

Variable   Type        Data/Info
--------------------------------
Math       type        <class 'IPython.core.display.Math'>
display    function    <function display at 0x7f0363054cb0>
eq         Add         3*q**2 + 2*q - 5/q - 4/q**3
expr       Mul         x*(-5**x/x + 2*y**2)
i          int         1
q          Symbol      q
sol        list        n=2
sol1       list        n=2
sym        module      <module 'sympy' from '/ho<...>kages/sympy/__init__.py'>
term1      Add         4*x + 5
term2      Symbol      x
term3      Add         x - 7
x          Symbol      x
y          Symbol      y


# Exercise 2

In [76]:
fxy = (4 + x)*(2 - y)

numrange = range(3)

for xi in numrange:
    for yi in numrange:
        print('When x = %g and y = %g, f(x,y) = %g'%(xi,yi,fxy.subs({x:xi,y:yi})))

When x = 0 and y = 0, f(x,y) = 8
When x = 0 and y = 1, f(x,y) = 4
When x = 0 and y = 2, f(x,y) = 0
When x = 1 and y = 0, f(x,y) = 10
When x = 1 and y = 1, f(x,y) = 5
When x = 1 and y = 2, f(x,y) = 0
When x = 2 and y = 0, f(x,y) = 12
When x = 2 and y = 1, f(x,y) = 6
When x = 2 and y = 2, f(x,y) = 0


# Matrices

In [77]:
import numpy as np

In [83]:
A = np.array([[1,2],[3,4]])
print(A)
display(Math(sym.latex(sym.sympify(A))))

[[1 2]
 [3 4]]


<IPython.core.display.Math object>

In [90]:
mat = np.zeros([4,6])
mat

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [94]:
numrange = range(4)

for rowi in numrange:
    for coli in numrange:
        mat[rowi,coli] = (-1)**(rowi + coli)
mat

array([[ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.],
       [ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.]])

## Exercise 3

In [103]:
x,y = sym.symbols('x y')

fxy = (4 + x) * (2 - y)

xyset = range(3)

outmat = np.zeros([len(xyset), len(xyset)])

for i in xyset:
    for j in xyset:
        outmat[i,j] = fxy.subs({x:i,y:i})

display(Math(sym.latex(sym.sympify(outmat))))

<IPython.core.display.Math object>

# Create a multiplication table

In [ ]:
for rowi in range(1,10):
    for coli in range(1,10):
        
matmul[rowi,coli] 