In [1]:
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, Math
%matplotlib inline

# Measure of Spread

In [5]:
np.random.seed(101)

n = np.random.randn(30)

n

array([ 2.70684984,  0.62813271,  0.90796945,  0.50382575,  0.65111795,
       -0.31931804, -0.84807698,  0.60596535, -2.01816824,  0.74012206,
        0.52881349, -0.58900053,  0.18869531, -0.75887206, -0.93323722,
        0.95505651,  0.19079432,  1.97875732,  2.60596728,  0.68350889,
        0.30266545,  1.69372293, -1.70608593, -1.15911942, -0.13484072,
        0.39052784,  0.16690464,  0.18450186,  0.80770591,  0.07295968])

### Range

In [6]:
np.max(n) - np.min(n)

4.72501808343733

### Quartile

In [13]:
## 1st quartile

q1 = np.percentile(n,25)
q1

-0.273198713596278

In [14]:
## 2nd quartile

q2 = np.percentile(n,50)
q2

0.34659664565946174

In [15]:
## 3rd quartile

q3 = np.percentile(n,75)
q3

0.7259687641768087

### Interquartile Range

In [17]:
IQR = q3 - q1
IQR

0.9991674777730867

### Variance

In [18]:
np.random.seed(101)
population = np.random.randn(100)
population

array([ 2.70684984e+00,  6.28132709e-01,  9.07969446e-01,  5.03825754e-01,
        6.51117948e-01, -3.19318045e-01, -8.48076983e-01,  6.05965349e-01,
       -2.01816824e+00,  7.40122057e-01,  5.28813494e-01, -5.89000533e-01,
        1.88695309e-01, -7.58872056e-01, -9.33237216e-01,  9.55056509e-01,
        1.90794322e-01,  1.97875732e+00,  2.60596728e+00,  6.83508886e-01,
        3.02665449e-01,  1.69372293e+00, -1.70608593e+00, -1.15911942e+00,
       -1.34840721e-01,  3.90527843e-01,  1.66904636e-01,  1.84501859e-01,
        8.07705914e-01,  7.29596753e-02,  6.38787013e-01,  3.29646299e-01,
       -4.97104023e-01, -7.54069701e-01, -9.43406403e-01,  4.84751647e-01,
       -1.16773316e-01,  1.90175480e+00,  2.38126959e-01,  1.99665229e+00,
       -9.93263500e-01,  1.96799505e-01, -1.13664459e+00,  3.66479606e-04,
        1.02598415e+00, -1.56597904e-01, -3.15791439e-02,  6.49825833e-01,
        2.15484644e+00, -6.10258856e-01, -7.55325340e-01, -3.46418504e-01,
        1.47026771e-01, -

In [19]:
sample = np.random.choice(population, 30)
sample

array([ 1.03512507,  1.86286414, -0.53823463,  0.90796945, -1.46751402,
       -0.75532534, -0.03116048,  0.66631932,  1.29276458, -0.9050999 ,
       -0.84807698,  0.64180551, -1.13664459, -1.70608593,  0.30266545,
        0.39052784, -0.86688504,  0.55876941, -0.73284515, -1.3829201 ,
       -1.46751402, -0.9050999 ,  0.68120929,  0.23033634, -1.46751402,
        0.23812696, -0.1565979 ,  0.48475165,  0.39052784,  1.02829316])

In [20]:
np.var(population)

1.068781607086222

In [21]:
np.var(sample)

0.904358760231582

### Standard Deviation

In [22]:
np.std(population)

1.0338189430873386

In [23]:
np.std(sample)

0.950977791660553